[workspace]
members = [
    "cli",
    "core",
    "parser",
    "playground-interpreter",
    "plugins",
    "projects",
    "tests",
]

[profile.release.package.wipple_playground_interpreter]
opt-level = "s"
