[package]
name = "wipple"
version = "0.0.0"
edition = "2018"

[dependencies]
num-rational = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "0.8", features = ["v4"] }
