[package]
name = "wipple"
version = "0.0.0"
edition = "2018"

[features]
use_serde = ["serde"]

[dependencies]
num-rational = "0.3"
rust-embed = "5.9.0"
serde = { version = "1.0", features = ["derive"], optional = true }
uuid = { version = "0.8", features = ["v4"] }
