on:
  workflow_dispatch:
  push:
    paths:
      - cli/**
      - core/**
      - parser/**
      - plugin-loader/**
      - tests/**

name: Test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Test
        run: cargo run --bin wipple_tests
